services:
  web:
    build: .
    command: >
      sh -c "uv run manage.py collectstatic --noinput && uv run manage.py migrate && uv run gunicorn --bind 0.0.0.0:8000 restaurantlookup.wsgi"
    ports:
      - "8000:8000"
    env_file:
      - .env.production