# Generated by Django 5.0.6 on 2024-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(default='https://www.yourdomain.com', max_length=50),
        ),
    ]
