# Generated by Django 5.0.6 on 2024-06-27 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiring_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 19, 21, 15, 406699, tzinfo=datetime.timezone.utc)),
        ),
    ]
