# Generated by Django 5.0.6 on 2024-06-28 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otp_expiring_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiring_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 28, 8, 33, 43, 504454, tzinfo=datetime.timezone.utc)),
        ),
    ]
