states_list = [
    ("IN_AN", "Andaman and Nicobar Islands"),
    ("IN_AP", " Andhra Pradesh"),
    ("IN_AR", "Arunachal Pradesh"),
    ("IN_AS", "Assam"),
    ("IN_BR", "Bihar"),
    ("IN_CH", "Chandigarh"),
    ("IN_CT", "Chhattisgarh"),
    ("IN_DD", "Daman and Diu"),
    ("IN_DL", "Delhi"),
    ("IN_GA", "Goa"),
    ("IN_GJ", "Gujarat"),
    ("IN_HR", "Haryana"),
    ("IN_HP", "Himachal Pradesh"),
    ("IN_JK", "Jammu and Kashmir"),
    ("IN_JH", "Jharkhand"),
    ("IN_KA", "Karnataka"),
    ("IN_KL", "Kerala"),
    ("IN_LA", "Ladakh"),
    ("IN_LD", "Lakshadweep"),
    ("IN_MH", "Maharashtra"),
    ("IN_MN", "Manipur"),
    ("IN_ML", "Meghalaya"),
    ("IN_MZ", "Mizoram"),
    ("IN_MP", "Madhya Pradesh"),
    ("IN_NR", "Nagaland"),
    ("IN_OR", "Odisha"),
    ("IN_PY", "Puducherry"),
    ("IN_PB", "Punjab"),
    ("IN_RJ", "Rajasthan"),
    ("IN_SK", "Sikkim"),
    ("IN_TN", "Tamil Nadu"),
    ("IN_TG", "Telangana"),
    ("IN_TR", "Tripura"),
    ("IN_UP", "Uttar Pradesh"),
    ("IN_UT", "Uttarakhand"),
    ("IN_WB", "West Bengal"),
]
countries = [
    (1, "Afghanistan"),
    (2, "Albania"),
    (3, "Algeria"),
    (4, "Andorra"),
    (5, "Angola"),
    (6, "Antigua and Barbuda"),
    (7, "Argentina"),
    (8, "Armenia"),
    (9, "Australia"),
    (10, "Austria"),
    (11, "Azerbaijan"),
    (12, "Bahamas"),
    (13, "Bahrain"),
    (14, "Bangladesh"),
    (15, "Barbados"),
    (16, "Belarus"),
    (17, "Belgium"),
    (18, "Belize"),
    (19, "Benin"),
    (20, "Bhutan"),
    (21, "Bolivia"),
    (22, "Bosnia and Herzegovina"),
    (23, "Botswana"),
    (24, "Brazil"),
    (25, "Brunei"),
    (26, "Bulgaria"),
    (27, "Burkina Faso"),
    (28, "Burundi"),
    (29, "Cabo Verde"),
    (30, "Cambodia"),
    (31, "Cameroon"),
    (32, "Canada"),
    (33, "Central African Republic"),
    (34, "Chad"),
    (35, "Chile"),
    (36, "China"),
    (37, "Colombia"),
    (38, "Comoros"),
    (39, "Congo"),
    (40, "Costa Rica"),
    (41, "Croatia"),
    (42, "Cuba"),
    (43, "Cyprus"),
    (44, "Czech Republic"),
    (45, "Democratic Republic of the Congo"),
    (46, "Denmark"),
    (47, "Djibouti"),
    (48, "Dominica"),
    (49, "Dominican Republic"),
    (50, "Ecuador"),
    (51, "Egypt"),
    (52, "El Salvador"),
    (53, "Equatorial Guinea"),
    (54, "Eritrea"),
    (55, "Estonia"),
    (56, "Eswatini"),
    (57, "Ethiopia"),
    (58, "Fiji"),
    (59, "Finland"),
    (60, "France"),
    (61, "Gabon"),
    (62, "Gambia"),
    (63, "Georgia"),
    (64, "Germany"),
    (65, "Ghana"),
    (66, "Greece"),
    (67, "Grenada"),
    (68, "Guatemala"),
    (69, "Guinea"),
    (70, "Guinea-Bissau"),
    (71, "Guyana"),
    (72, "Haiti"),
    (73, "Honduras"),
    (74, "Hungary"),
    (75, "Iceland"),
    (76, "India"),
    (77, "Indonesia"),
    (78, "Iran"),
    (79, "Iraq"),
    (80, "Ireland"),
    (81, "Israel"),
    (82, "Italy"),
    (83, "Ivory Coast"),
    (84, "Jamaica"),
    (85, "Japan"),
    (86, "Jordan"),
    (87, "Kazakhstan"),
    (88, "Kenya"),
    (89, "Kiribati"),
    (90, "Korea North"),
    (91, "Korea South"),
    (92, "Kuwait"),
    (93, "Kyrgyzstan"),
    (94, "Laos"),
    (95, "Latvia"),
    (96, "Lebanon"),
    (97, "Lesotho"),
    (98, "Liberia"),
    (99, "Libya"),
    (100, "Liechtenstein"),
    (101, "Lithuania"),
    (102, "Luxembourg"),
    (103, "Madagascar"),
    (104, "Malawi"),
    (105, "Malaysia"),
    (106, "Maldives"),
    (107, "Mali"),
    (108, "Malta"),
    (109, "Marshall Islands"),
    (110, "Mauritania"),
    (111, "Mauritius"),
    (112, "Mexico"),
    (113, "Micronesia"),
    (114, "Moldova"),
    (115, "Monaco"),
    (116, "Mongolia"),
    (117, "Montenegro"),
    (118, "Morocco"),
    (119, "Mozambique"),
    (120, "Myanmar"),
    (121, "Namibia"),
    (122, "Nauru"),
    (123, "Nepal"),
    (124, "Netherlands"),
    (125, "New Zealand"),
    (126, "Nicaragua"),
    (127, "Niger"),
    (128, "Nigeria"),
    (129, "North Macedonia"),
    (130, "Norway"),
    (131, "Oman"),
    (132, "Pakistan"),
    (133, "Palau"),
    (134, "Palestine"),
    (135, "Panama"),
    (136, "Papua New Guinea"),
    (137, "Paraguay"),
    (138, "Peru"),
    (139, "Philippines"),
    (140, "Poland"),
    (141, "Portugal"),
    (142, "Qatar"),
    (143, "Romania"),
    (144, "Russia"),
    (145, "Rwanda"),
    (146, "Saint Kitts and Nevis"),
    (147, "Saint Lucia"),
    (148, "Saint Vincent and the Grenadines"),
    (149, "Samoa"),
    (150, "San Marino"),
    (151, "Sao Tome and Principe"),
    (152, "Saudi Arabia"),
    (153, "Senegal"),
    (154, "Serbia"),
    (155, "Seychelles"),
    (156, "Sierra Leone"),
    (157, "Singapore"),
    (158, "Slovakia"),
    (159, "Slovenia"),
    (160, "Solomon Islands"),
    (161, "Somalia"),
    (162, "South Africa"),
    (163, "South Sudan"),
    (164, "Spain"),
    (165, "Sri Lanka"),
    (166, "Sudan"),
    (167, "Suriname"),
    (168, "Sweden"),
    (169, "Switzerland"),
    (170, "Syria"),
    (171, "Taiwan"),
    (172, "Tajikistan"),
    (173, "Tanzania"),
    (174, "Thailand"),
    (175, "Timor-Leste"),
    (176, "Togo"),
    (177, "Tonga"),
    (178, "Trinidad and Tobago"),
    (179, "Tunisia"),
    (180, "Turkey"),
    (181, "Turkmenistan"),
    (182, "Tuvalu"),
    (183, "Uganda"),
    (184, "Ukraine"),
    (185, "United Arab Emirates"),
    (186, "United Kingdom"),
    (187, "United States"),
    (188, "Uruguay"),
    (189, "Uzbekistan"),
    (190, "Vanuatu"),
    (191, "Vatican City"),
    (192, "Venezuela"),
    (193, "Vietnam"),
    (194, "Yemen"),
    (195, "Zambia"),
    (196, "Zimbabwe")
]
country_phone_codes = [
    ("+93", "Afghanistan"),
    ("+355", "Albania"),
    ("+213", "Algeria"),
    ("+376", "Andorra"),
    ("+244", "Angola"),
    ("+1-268", "Antigua and Barbuda"),
    ("+54", "Argentina"),
    ("+374", "Armenia"),
    ("+61", "Australia"),
    ("+43", "Austria"),
    ("+994", "Azerbaijan"),
    ("+1-242", "Bahamas"),
    ("+973", "Bahrain"),
    ("+880", "Bangladesh"),
    ("+1-246", "Barbados"),
    ("+375", "Belarus"),
    ("+32", "Belgium"),
    ("+501", "Belize"),
    ("+229", "Benin"),
    ("+975", "Bhutan"),
    ("+591", "Bolivia"),
    ("+387", "Bosnia and Herzegovina"),
    ("+267", "Botswana"),
    ("+55", "Brazil"),
    ("+673", "Brunei"),
    ("+359", "Bulgaria"),
    ("+226", "Burkina Faso"),
    ("+257", "Burundi"),
    ("+238", "Cabo Verde"),
    ("+855", "Cambodia"),
    ("+237", "Cameroon"),
    ("+1", "Canada"),
    ("+236", "Central African Republic"),
    ("+235", "Chad"),
    ("+56", "Chile"),
    ("+86", "China"),
    ("+57", "Colombia"),
    ("+269", "Comoros"),
    ("+242", "Congo"),
    ("+506", "Costa Rica"),
    ("+385", "Croatia"),
    ("+53", "Cuba"),
    ("+357", "Cyprus"),
    ("+420", "Czech Republic"),
    ("+243", "Democratic Republic of the Congo"),
    ("+45", "Denmark"),
    ("+253", "Djibouti"),
    ("+1-767", "Dominica"),
    ("+1-809", "Dominican Republic"),
    ("+593", "Ecuador"),
    ("+20", "Egypt"),
    ("+503", "El Salvador"),
    ("+240", "Equatorial Guinea"),
    ("+291", "Eritrea"),
    ("+372", "Estonia"),
    ("+268", "Eswatini"),
    ("+251", "Ethiopia"),
    ("+679", "Fiji"),
    ("+358", "Finland"),
    ("+33", "France"),
    ("+241", "Gabon"),
    ("+220", "Gambia"),
    ("+995", "Georgia"),
    ("+49", "Germany"),
    ("+233", "Ghana"),
    ("+30", "Greece"),
    ("+1-473", "Grenada"),
    ("+502", "Guatemala"),
    ("+224", "Guinea"),
    ("+245", "Guinea-Bissau"),
    ("+592", "Guyana"),
    ("+509", "Haiti"),
    ("+504", "Honduras"),
    ("+36", "Hungary"),
    ("+354", "Iceland"),
    ("+91", "India"),
    ("+62", "Indonesia"),
    ("+98", "Iran"),
    ("+964", "Iraq"),
    ("+353", "Ireland"),
    ("+972", "Israel"),
    ("+39", "Italy"),
    ("+225", "Ivory Coast"),
    ("+1-876", "Jamaica"),
    ("+81", "Japan"),
    ("+962", "Jordan"),
    ("+7", "Kazakhstan"),
    ("+254", "Kenya"),
    ("+686", "Kiribati"),
    ("+850", "Korea North"),
    ("+82", "Korea South"),
    ("+965", "Kuwait"),
    ("+996", "Kyrgyzstan"),
    ("+856", "Laos"),
    ("+371", "Latvia"),
    ("+961", "Lebanon"),
    ("+266", "Lesotho"),
    ("+231", "Liberia"),
    ("+218", "Libya"),
    ("+423", "Liechtenstein"),
    ("+370", "Lithuania"),
    ("+352", "Luxembourg"),
    ("+261", "Madagascar"),
    ("+265", "Malawi"),
    ("+60", "Malaysia"),
    ("+960", "Maldives"),
    ("+223", "Mali"),
    ("+356", "Malta"),
    ("+692", "Marshall Islands"),
    ("+222", "Mauritania"),
    ("+230", "Mauritius"),
    ("+52", "Mexico"),
    ("+691", "Micronesia"),
    ("+373", "Moldova"),
    ("+377", "Monaco"),
    ("+976", "Mongolia"),
    ("+382", "Montenegro"),
    ("+212", "Morocco"),
    ("+258", "Mozambique"),
    ("+95", "Myanmar"),
    ("+264", "Namibia"),
    ("+674", "Nauru"),
    ("+977", "Nepal"),
    ("+31", "Netherlands"),
    ("+64", "New Zealand"),
    ("+505", "Nicaragua"),
    ("+227", "Niger"),
    ("+234", "Nigeria"),
    ("+389", "North Macedonia"),
    ("+47", "Norway"),
    ("+968", "Oman"),
    ("+92", "Pakistan"),
    ("+680", "Palau"),
    ("+970", "Palestine"),
    ("+507", "Panama"),
    ("+675", "Papua New Guinea"),
    ("+595", "Paraguay"),
    ("+51", "Peru"),
    ("+63", "Philippines"),
    ("+48", "Poland"),
    ("+351", "Portugal"),
    ("+974", "Qatar"),
    ("+40", "Romania"),
    ("+7", "Russia"),
    ("+250", "Rwanda"),
    ("+1-869", "Saint Kitts and Nevis"),
    ("+1-758", "Saint Lucia"),
    ("+1-784", "Saint Vincent and the Grenadines"),
    ("+685", "Samoa"),
    ("+378", "San Marino"),
    ("+239", "Sao Tome and Principe"),
    ("+966", "Saudi Arabia"),
    ("+221", "Senegal"),
    ("+381", "Serbia"),
    ("+248", "Seychelles"),
    ("+232", "Sierra Leone"),
    ("+65", "Singapore"),
    ("+421", "Slovakia"),
    ("+386", "Slovenia"),
    ("+677", "Solomon Islands"),
    ("+252", "Somalia"),
    ("+27", "South Africa"),
    ("+211", "South Sudan"),
    ("+34", "Spain"),
    ("+94", "Sri Lanka"),
    ("+249", "Sudan"),
    ("+597", "Suriname"),
    ("+46", "Sweden"),
    ("+41", "Switzerland"),
    ("+963", "Syria"),
    ("+886", "Taiwan"),
    ("+992", "Tajikistan"),
    ("+255", "Tanzania"),
    ("+66", "Thailand"),
    ("+670", "Timor-Leste"),
    ("+228", "Togo"),
    ("+676", "Tonga"),
    ("+1-868", "Trinidad and Tobago"),
    ("+216", "Tunisia"),
    ("+90", "Turkey"),
    ("+993", "Turkmenistan"),
    ("+688", "Tuvalu"),
    ("+256", "Uganda"),
    ("+380", "Ukraine"),
    ("+971", "United Arab Emirates"),
    ("+44", "United Kingdom"),
    ("+1", "United States"),
    ("+598", "Uruguay"),
    ("+998", "Uzbekistan"),
    ("+678", "Vanuatu"),
    ("+379", "Vatican City"),
    ("+58", "Venezuela"),
    ("+84", "Vietnam"),
    ("+967", "Yemen"),
    ("+260", "Zambia"),
    ("+263", "Zimbabwe")
]

country_phone_codes = [
    (each[0], f'{each[0]} ({each[1]})') for each in country_phone_codes
]
rating_nums = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')]

days = [(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]